repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['-l 80',--safe, --target-version=py310]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-json

        language_version: python3

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
      -   id: mypy
          verbose: true
          args: [--ignore-missing-imports,--no-strict-optional, ]
          entry: bash -c 'mypy "$@" || true' --

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [python]

        args:
         -  "-rn" # Only display messages
         -   "-sn" # Don't display the score
        entry: bash -c 'pylint "$@" || true' --
