version: "3.9"

services:
  omnecal-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: omnecal-backend
    depends_on:
      - db_1
      - rabbitmq
      - redis
    ports:
      - 8000:7777
    volumes:
      - ./:/app
    restart: always
    command: uvicorn main:app --host=0.0.0.0 --port 7777 --reload

  rabbitmq:
    image: rabbitmq:3.10.6-management
    container_name: Queue
    restart: always
    ports:
      - 5672:5672 # Broker Connection Port
      - 15672:15672 # Broker Management UI
    networks:
      - default

  redis:
    image: redis:7.0.4
    container_name: redis-cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/redis-cache
    networks:
      - default

  db_1:
    image: postgres:14.1-alpine
    container_name: omnecal_pg1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omnecal
    ports:
      - 5432:5432
    volumes:
      - pg_data1:/db_1/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db_1

volumes:
  pg_data1:
  cache:
  pgadmin:


networks:
  default:
    name: omnecal-network
