"""empty message

Revision ID: 195cb059d933
Revises:
Create Date: 2022-07-26 12:26:45.490119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "195cb059d933"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("last_name", sa.String(length=32), nullable=True),
        sa.Column("mobile_number", sa.String(length=15), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "student", "regular", "elder", "disable", name="usercategory"
            ),
            nullable=True,
        ),
        sa.Column("password", sa.String(length=250), nullable=True),
        sa.Column("is_driver", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Users_category"), "Users", ["category"], unique=False
    )
    op.create_index(op.f("ix_Users_id"), "Users", ["id"], unique=True)
    op.create_index(
        op.f("ix_Users_mobile_number"), "Users", ["mobile_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Users_mobile_number"), table_name="Users")
    op.drop_index(op.f("ix_Users_id"), table_name="Users")
    op.drop_index(op.f("ix_Users_category"), table_name="Users")
    op.drop_table("Users")
    # ### end Alembic commands ###
